CREATE TABLE public.case_studies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT now() NOT NULL,
    prompt text,
    generated_text text,
    image_url text
);
